### ISSUE TITLE
The most desirable repository for archicad community

### ISSUE THREAD

**Issue by arthurvilarinho** [kuvbur/PyGDL#1]
Hello! Actually, this is not an issue, but I need guidance.

I have been trying to find this kind of Python-GDL translator for so long. I think it’s something everyone should know about. Python is such a powerful and popular programming language, and it’s much easier to use than GDL (in my opinion). This translation should benefit a lot of users.

I was struggling with my own beginner’s script one week ago, thinking to myself why nobody had thought of this before. Luckily, I just found your script, and it seems to be so advanced and complete! I’m thrilled!

I’m now testing it and trying to understand everything, but I think I’m doing something wrong.

If I may ask, is there a proper way that you recommend for working with it? What’s your advice for the workflow?

**Comment by kuvbur** [comment]
@arthurvilarinho Good afternoon. The project was conceived as a way to automate adding code to a large number of objects. The main purpose is conversion to different versions, batch addition of parameters and code.
